### PR TITLE
Support for systemd and xenial

### PR DESCRIPTION
**Pull request by andrewschoen**
This also moves all playbooks into `deploy/playbooks/examples` and git ignores any `*.yml` files in `deploy/playbooks` to allow for local customization.

### CODE REVIEW

**Comment by alfredodeza** [comment]
For this to be built we would need a new place for mita that is based off on xenial. Can we do that first before this is merged? If we do it the other way around we risk needing fixes to mita and holding off because this got in and we can't deploy on the current server

**Comment by djgalloway** [comment]
@alfredodeza @andrewschoen What's the status here?  I think it'd be best to get this merged before I deploy mita on the new Jenkins master.

**Comment by andrewschoen** [comment]
@djgalloway I think this is good to go, however it hasn't been tested in quite some time.

**Comment by alfredodeza** [comment]
@andrewschoen  @djgalloway this means that we no longer can deploy mita for current jenkins.ceph.com

**Comment by djgalloway** [comment]
@alfredodeza It should be redeployed to be collocated on jenkins.ceph.com anyway IMO.  Then we can get rid of the mita VM.  jenkins.ceph.com is running Xenial.

**Comment by andrewschoen** [comment]
+1 to collocating on jenkins.ceph.com

**Pull request merged**
