### PR TITLE
install and link python2.7

### PR DESCRIPTION
**Pull request by alfredodeza**
Signed-off-by: Alfredo Deza <adeza@redhat.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
Is the symlink necessary? When I install python2.7 on xenial,  `/usr/bin/python` is present and Ansible runs fine.

**Comment by alfredodeza** [comment]
At least on the OVH images it was (after installing python2.7):

    -bash: /usr/bin/python: No such file or directory

And:

    /usr/bin/env: ‘python’: No such file or directory

**Comment by ktdreyer** [comment]
Oh! I just double-checked, and the package you want is `python`, not `python2.7`

**Comment by ktdreyer** [comment]
See https://github.com/ceph/mita/pull/64

**Pull request merged**
